language: node_js
node_js:
- '4.6'
cache:
  directories:
  - node_modules
script:
- npm i -g gulp
- npm i
- gulp build
- git config user.email "guiilherme.bayer@gmail.com"
- git config user.name "guuibayer"
- git add dist
- git commit -m "Initial dist subtree commit"
- git subtree push --prefix dist origin master

deploy:
  provider: heroku
  app: notificat
  api_key:
    secure: $HEROKU
