language: node_js
node_js:
  - "4.6"
cache:
  directories:
  - node_modules

before_script:
- npm install -g gulp

script:
- npm i

after_success:
- gulp build

deploy:
   provider: heroku
   app: notificat
   api_key:
      secure: 
