language: node_js
node_js:
- '4.6'
cache:
  directories:
  - node_modules
before_script:
- npm install -g gulp
script:
- npm i

deploy:
  provider: heroku
  script: gulp build
  app: notificat
  api_key:
    secure: $HEROKU
