language: node_js
node_js:
- '4.6'
cache:
  directories:
  - node_modules
script:
- npm i -g gulp
- npm i
- git checkout develop
- git config --global user.name "guuibayer"
- git config --global user.email "guiilherme.bayer@gmail.com"
- gulp babel
- gulp deploy
# - git add dist
# - git commit -m "Initial dist subtree commit"
# - git push origin `git subtree split --prefix dist origin master`:develop --force

deploy:
  provider: heroku
  app: notificat
  api_key:
    secure: $HEROKU
