language: node_js
node_js:
- '4.6'
cache:
  directories:
  - node_modules

script:
- npm i -g gulp
- npm i
- git checkout develop
- git config --global user.name "guuibayer"
- git config --global user.email "guiilherme.bayer@gmail.com"
- gulp babel
- gulp copyToBuild

after_success:
- git checkout master
- rsync -avvz -e -o "StrictHostKeyChecking no" $LOCAL_DIRECTORY $PROD_HOST_USER@$PROD_HOST_IP:$PROD_DIRECTORY