language: node_js
node_js:
- '4.6'
cache:
  directories:
  - node_modules
before_script:
- npm install -g gulp
script:
- npm i
after_success:
- gulp build
deploy:
  provider: heroku
  app: notificat
  api_key:
    secure: wTG3fZqHs1ik3Jn3nHRClVtzL/F1em2rRjw0zi3VmeH1+jid8DBY05NlDblqu751/UTkIbHiq9EpvuWHdx+VS3HhD7X3tnbNMGJQC/jxIlbk17MKghfw3f6p99gBBEwKT0DTBbM45B48C1tkDl5rDQOZ9p6N98OxMTjYS8aRi6WO8GN1maxn4ohbMLgv79czCRObHb78CuU/aT3pLUGbc928toD4KBJiAOAyAMAW2L1LD23Ea3F1uUOWGnwv+ZNjz29MKnWNcih79SVzdPDZPoTdDHUggzotj0Ywqp3nOMskWeb37iVf4psYFiD+Lw2PJ2gDRthyCZjfObSb5PYAgF88FO6BVQJpFjr7fBLVwZaGvYY/K1gMXjZqiInZ0PYHbm8wj52uP8QnbU87CZzmpniUQBKIhsh17Afvgm5TkURykP6UU40bFeof8cuEb/ig/53+bRNYCA9dvUbMVC1AGdQ+gEnf17MWwdmasQMKOm8gAIuzCyOH1fmIMe9S4tevRQDLPSG8xd9HgVKOMZUqIhClclkdQMZtCiDGHi/Lcg+CS4Bu5BKeh0SEjYKSJ8aBDu+PcIUlmD4b/jrVWRihAPLkp3m/lhDC1euufGjswNZSLqWfdFCWeWNvSvkssX5Jmr//zVZlPcFKd2KCOYPTJAvGeJQH04cD0IIIO5rZ0QE=
